version: '3.8'

volumes:
  pgdata:


services:
  postgres:
    image: postgres:15
    container_name: postgres15
    environment:
      POSTGRES_DB: ban_db
      POSTGRES_USER: ban_service
      POSTGRES_PASSWORD: banpasswd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data